# Site settings
title: Towards a Post-Work Society
description: Designing a Society where every member has a basic quality of life without having to "work to live"

# GitHub Pages settings
#url: "https://agethegod.github.io"
#baseurl: "/PostWorkSociety"

theme: just-the-docs
nav_enabled: true
heading_anchors: true
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
#markdown: kramdown

# Mermaid configuration : Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
mermaid:
  version: "11.15.0"

