# Site settings
title: Towards a Post-Work Society
description: A society designed so that every member has a basic quality of life without having to "work to live"

# GitHub Pages settings
url: "https://agetheod.github.io"
baseurl: "/Post-Work-Society"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - CONTRIBUTING.md
  - .git
